### ISSUE TITLE
Pre-training Equipment and Time

### ISSUE THREAD

**Issue by changyuying** [GeekDream-x/IDOL#1]
Hello, could you please tell me the equipment and quantity required during the incremental pre-training phase, as well as the training time?

**Comment by GeekDream-x** [comment]
Hi, I ran all the experiments on 8 pieces of TeslaA100*48G. Take RoBERTa for example, the training time is about 52h. If you use larger models or training steps, the time would be longer.

**Comment by changyuying** [comment]
OK, thank you!
