### ISSUE TITLE
ImportError: cannot import name 'DebertaV2ForMultipleChoice' from 'transformers'

### ISSUE THREAD

**Issue by liqinga** [GeekDream-x/IDOL#2]
<img width="1237" alt="image" src="https://github.com/GeekDream-x/IDOL/assets/68682858/7d7861d8-31cf-4b5f-b301-12feaa9acbcb">
在运行 sh run_ft.sh 时会在finetuning.py中出现ImportError: cannot import name 'DebertaV2ForMultipleChoice' from 'transformers'这个报错，我尝试进入到transformers包中找到这个类也没有找到。

**Comment by GeekDream-x** [comment]
@liqinga 您好，由于二次预训练和精调阶段transformers版本不一致导致，现已更新，直接使用本项目根目录提供的transformers即可。
